# Warnings currently triggered by your code
- ignore: {name: "Eta reduce"} # 6 hints
- ignore: {name: "Move brackets to avoid $"} # 19 hints
- ignore: {name: "Redundant bracket"} # 118 hints
- ignore: {name: "Redundant if"} # 1 hint
- ignore: {name: "Use newtype instead of data"} # 1 hint
- ignore: {name: "Use null"} # 3 hints
- ignore: {name: "Use optional"} # 1 hint