name:                odd-jobs
version:             0.1.0.0
synopsis: A full-featured PostgreSQL-backed job queue (with an admin UI)
description: |
  - Background jobs library for Haskell.
  - Inspired by the Delayed Jobs library in Rails.
  - Queue backend is a Postgres table.
  - Queue is monitored using, both, LISTEN/NOTIFY and polling the DB.
  - Comes with an in-built admin UI.
homepage:            https://github.com/saurabhnanda/odd-jobs/
license:             BSD3
author:              Saurabh Nanda
maintainer:          saurabhnanda@gmail.com
copyright:           2019 Saurabh Nanda
category:            Web
extra-source-files:
- README.md

ghc-options: 
  - -Wall 
  - -fno-warn-orphans 
  - -fno-warn-unused-imports 
  - -fno-warn-dodgy-exports 
  - -Werror=missing-fields

default-extensions:
  - NamedFieldPuns
  - LambdaCase
  - TemplateHaskell
  - ScopedTypeVariables
  - GeneralizedNewtypeDeriving
  - QuasiQuotes
  - OverloadedStrings

dependencies:
  - base >= 4.7 && < 5
  - text
  - postgresql-simple
  - bytestring
  - safe
  - text-conversions
  - aeson
  - resource-pool
  - unliftio
  - unliftio-core
  - mtl
  - monad-logger
  - fast-logger
  - either
  - time
  - unix
  - monad-control
  - string-conv
  - hostname
  - lucid
  - timing-convenience
  - friendly-time
  - servant
  - servant-server
  - servant-lucid
  - warp
  - unordered-containers
  - optparse-applicative
  - direct-daemonize
  - filepath
  - directory


library:
  source-dirs:
    - src
  exposed-modules:
    - OddJobs.Job
    - OddJobs.Migrations
    - OddJobs.Web
    - OddJobs.Endpoints
    - OddJobs.Cli
    - OddJobs.Types

executables:
  devel:
    source-dirs:      dev
    main:             DevelMain.hs
    ghc-options:
      - -threaded
      - -with-rtsopts=-N
      - -main-is DevelMain
    dependencies:
      - foreign-store
      - odd-jobs

tests:
  jobrunner:
    ghc-options:
      - -threaded
    main: Test
    source-dirs: test
    dependencies:
      - tasty
      - tasty-discover
      - hedgehog
      - tasty-hedgehog
      - odd-jobs
      - tasty-hunit
      - random
      - monad-control
      - mmorph
      - lifted-base
      - lifted-async
      - containers
