name:                odd-jobs
version:             0.1.0.0
synopsis: A full-featured PostgreSQL-backed job queue (with an admin UI)
description: |
  Something long comes here
  Something very long
homepage:            https://github.com/saurabhnanda/haskell-pg-queue#readme
license:             BSD3
author:              Saurabh Nanda
maintainer:          saurabhnanda@gmail.com
copyright:           2019 Saurabh Nanda
category:            Web
extra-source-files:
- README.md

ghc-options: 
  - -Wall 
  - -fno-warn-orphans 
  - -fno-warn-unused-imports 
  - -fno-warn-dodgy-exports 
  - -O0
  - -Werror=missing-fields

default-extensions:
  - NamedFieldPuns
  - LambdaCase
  - TemplateHaskell
  - ScopedTypeVariables
  - GeneralizedNewtypeDeriving
  - QuasiQuotes
  - OverloadedStrings

dependencies:
  - base >= 4.7 && < 5
  - text
  - postgresql-simple
  - bytestring
  - safe
  - text-conversions
  - process
  - aeson
  - resource-pool
  - timeit
  - unliftio
  - unliftio-core
  - mtl
  - template-haskell
  - monad-logger
  - fast-logger
  - either
  - time
  - exceptions
  - unix
  - monad-control
  - string-conv
  - hostname
  - async
  - lucid
  - blaze-builder
  - timing-convenience
  - servant
  - servant-server
  - servant-lucid
  - warp
  - friendly-time
  - unordered-containers
  - foreign-store
  - optparse-applicative
  - direct-daemonize
  - filepath
  - directory


library:
  source-dirs:
    - src
    - dev
  exposed-modules:
    - OddJobs.Job
    - OddJobs.Migrations
    - OddJobs.Web
    - OddJobs.Endpoints
    - OddJobs.Cli
    - DevelMain

# executables:
#   devel:
#     source-dirs:      dev
#     main:             DevelMain.hs
#     dependencies:
#       - foreign-store
#       - haskell-pg-queue

executables:
  odd-jobs-cli-parser:
    source-dirs: test
    ghc-options:
      - -threaded
      - -with-rtsopts=-N
      - -main-is CliParser
    main: CliParser.hs
    other-modules: []
    dependencies:
      - odd-jobs

tests:
  jobrunner:
    ghc-options:
      - -threaded
    main: Test
    source-dirs: test
    dependencies:
      - tasty
      - tasty-discover
      - hedgehog
      - tasty-hedgehog
      - odd-jobs
      - tasty-hunit
      - random
      - monad-control
      - mmorph
      - lifted-base
      - lifted-async
      - containers
