name: CI

on:
  pull_request:
    branches:
        - '*'


jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    env:
      STACK_ROOT: ${{ github.workspace }}/.stack
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest
          # windows-latest # TODO add windows support
        ]
        resolver: [nightly, lts-16, lts-18, lts-20, lts-21]

    steps:
      - name: Clone project
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            ${{ github.workspace }}/.stack
          key: ${{ runner.os }}-${{ matrix.resolver }}-haskell-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.resolver }}-haskell-

      - name: Build and run tests
        shell: bash
        run: |
            set -ex
            curl -sSL https://get.haskellstack.org/ | sh -s - -f
            stack test --fast --no-terminal --stack-yaml=${{ matrix.resolver }}.stack.yaml
